var searchData=
[
  ['l1linfparameters_0',['l1linfParameters',['http://www.dealii.org/developer/doxygen/deal.II/structMatrixScaling_1_1AdditionalData_1_1l1linfParameters.html',1,'MatrixScaling::AdditionalData']]],
  ['lagrangeequidistant_1',['LagrangeEquidistant',['http://www.dealii.org/developer/doxygen/deal.II/classPolynomials_1_1LagrangeEquidistant.html',1,'Polynomials']]],
  ['lambdaoptimizer_2',['LambdaOptimizer',['http://www.dealii.org/developer/doxygen/deal.II/structDifferentiation_1_1SD_1_1internal_1_1LambdaOptimizer.html',1,'Differentiation::SD::internal']]],
  ['lapackfullmatrix_3',['LAPACKFullMatrix',['http://www.dealii.org/developer/doxygen/deal.II/classLAPACKFullMatrix.html',1,'']]],
  ['lapackfullmatrix_3c_20double_20_3e_4',['LAPACKFullMatrix&lt; double &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLAPACKFullMatrix.html',1,'']]],
  ['lapackfullmatrix_3c_20number_20_3e_5',['LAPACKFullMatrix&lt; Number &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLAPACKFullMatrix.html',1,'']]],
  ['lapackfullmatrix_3c_20number_20_3e_6',['LAPACKFullMatrix&lt; number &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLAPACKFullMatrix.html',1,'']]],
  ['laplaceoperator_7',['LaplaceOperator',['http://www.dealii.org/developer/doxygen/deal.II/classMatrixFreeOperators_1_1LaplaceOperator.html',1,'MatrixFreeOperators']]],
  ['lazy_8',['Lazy',['http://www.dealii.org/developer/doxygen/deal.II/classLazy.html',1,'']]],
  ['lazy_3c_20fevaluesviews_3a_3ascalar_3c_20dim_2c_20spacedim_20_3e_20_3e_9',['Lazy&lt; FEValuesViews::Scalar&lt; dim, spacedim &gt; &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLazy.html',1,'']]],
  ['lazy_3c_20fevaluesviews_3a_3asymmetrictensor_3c_202_2c_20dim_2c_20spacedim_20_3e_20_3e_10',['Lazy&lt; FEValuesViews::SymmetricTensor&lt; 2, dim, spacedim &gt; &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLazy.html',1,'']]],
  ['lazy_3c_20fevaluesviews_3a_3atensor_3c_202_2c_20dim_2c_20spacedim_20_3e_20_3e_11',['Lazy&lt; FEValuesViews::Tensor&lt; 2, dim, spacedim &gt; &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLazy.html',1,'']]],
  ['lazy_3c_20fevaluesviews_3a_3avector_3c_20dim_2c_20spacedim_20_3e_20_3e_12',['Lazy&lt; FEValuesViews::Vector&lt; dim, spacedim &gt; &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLazy.html',1,'']]],
  ['lazy_3c_20std_3a_3aunique_5fptr_3c_20fe_5fq_3c_20dim_20_3e_20_3e_20_3e_13',['Lazy&lt; std::unique_ptr&lt; FE_Q&lt; dim &gt; &gt; &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLazy.html',1,'']]],
  ['legendre_14',['Legendre',['http://www.dealii.org/developer/doxygen/deal.II/classFESeries_1_1Legendre.html',1,'FESeries::Legendre&lt; int dim, int spacedim &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classPolynomials_1_1Legendre.html',1,'Polynomials::Legendre']]],
  ['levelaccessor_15',['LevelAccessor',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1TriaAccessorImplementation_1_1LevelAccessor.html',1,'internal::TriaAccessorImplementation']]],
  ['levelaccessor_3c_20false_20_3e_16',['LevelAccessor&lt; false &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1TriaAccessorImplementation_1_1LevelAccessor_3_01false_01_4.html',1,'internal::TriaAccessorImplementation']]],
  ['levelaccessor_3c_20true_20_3e_17',['LevelAccessor&lt; true &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1TriaAccessorImplementation_1_1LevelAccessor_3_01true_01_4.html',1,'internal::TriaAccessorImplementation']]],
  ['levelequalto_18',['LevelEqualTo',['http://www.dealii.org/developer/doxygen/deal.II/classIteratorFilters_1_1LevelEqualTo.html',1,'IteratorFilters']]],
  ['levelsetdescription_19',['LevelSetDescription',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1MeshClassifierImplementation_1_1LevelSetDescription.html',1,'NonMatching::internal::MeshClassifierImplementation']]],
  ['levelsetdescription_3c_20dim_20_3e_20',['LevelSetDescription&lt; dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1MeshClassifierImplementation_1_1LevelSetDescription.html',1,'NonMatching::internal::MeshClassifierImplementation']]],
  ['line_21',['Line',['http://www.dealii.org/developer/doxygen/deal.II/structDynamicSparsityPattern_1_1Line.html',1,'DynamicSparsityPattern']]],
  ['linearindexiterator_22',['LinearIndexIterator',['http://www.dealii.org/developer/doxygen/deal.II/classLinearIndexIterator.html',1,'']]],
  ['linearindexiterator_3c_20iterator_2c_20accessor_20_3e_23',['LinearIndexIterator&lt; Iterator, Accessor &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLinearIndexIterator.html',1,'']]],
  ['linearindexiterator_3c_20iterator_3c_20tabletype_2c_20constness_2c_20storage_5forder_20_3e_2c_20accessor_3c_20tabletype_2c_20constness_2c_20storage_5forder_20_3e_20_3e_24',['LinearIndexIterator&lt; Iterator&lt; TableType, Constness, storage_order &gt;, Accessor&lt; TableType, Constness, storage_order &gt; &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLinearIndexIterator.html',1,'']]],
  ['linearoperator_25',['LinearOperator',['http://www.dealii.org/developer/doxygen/deal.II/classLinearOperator.html',1,'']]],
  ['linearoperator_3c_20range_2c_20domain_2c_20blockpayload_3a_3ablocktype_20_3e_26',['LinearOperator&lt; Range, Domain, BlockPayload::BlockType &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLinearOperator.html',1,'']]],
  ['linearoperator_3c_20typename_20range_3a_3ablocktype_2c_20typename_20domain_3a_3ablocktype_2c_20typename_20blockpayload_3a_3ablocktype_20_3e_27',['LinearOperator&lt; typename Range::BlockType, typename Domain::BlockType, typename BlockPayload::BlockType &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLinearOperator.html',1,'']]],
  ['linearsolverwrapper_28',['LinearSolverWrapper',['http://www.dealii.org/developer/doxygen/deal.II/classSUNDIALS_1_1internal_1_1LinearSolverWrapper.html',1,'SUNDIALS::internal']]],
  ['linearsolverwrapper_3c_20vectortype_20_3e_29',['LinearSolverWrapper&lt; VectorType &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classSUNDIALS_1_1internal_1_1LinearSolverWrapper.html',1,'SUNDIALS::internal']]],
  ['list_30',['List',['http://www.dealii.org/developer/doxygen/deal.II/classPatterns_1_1List.html',1,'Patterns']]],
  ['lobatto_31',['Lobatto',['http://www.dealii.org/developer/doxygen/deal.II/classPolynomials_1_1Lobatto.html',1,'Polynomials']]],
  ['localintegrator_32',['LocalIntegrator',['http://www.dealii.org/developer/doxygen/deal.II/classMeshWorker_1_1LocalIntegrator.html',1,'MeshWorker']]],
  ['locallyownedcell_33',['LocallyOwnedCell',['http://www.dealii.org/developer/doxygen/deal.II/classIteratorFilters_1_1LocallyOwnedCell.html',1,'IteratorFilters']]],
  ['locallyownedlevelcell_34',['LocallyOwnedLevelCell',['http://www.dealii.org/developer/doxygen/deal.II/classIteratorFilters_1_1LocallyOwnedLevelCell.html',1,'IteratorFilters']]],
  ['localresults_35',['LocalResults',['http://www.dealii.org/developer/doxygen/deal.II/classMeshWorker_1_1LocalResults.html',1,'MeshWorker']]],
  ['logstream_36',['LogStream',['http://www.dealii.org/developer/doxygen/deal.II/classLogStream.html',1,'']]],
  ['loopcontrol_37',['LoopControl',['http://www.dealii.org/developer/doxygen/deal.II/classMeshWorker_1_1LoopControl.html',1,'MeshWorker']]],
  ['lowstoragerungekutta_38',['LowStorageRungeKutta',['http://www.dealii.org/developer/doxygen/deal.II/classTimeStepping_1_1LowStorageRungeKutta.html',1,'TimeStepping']]],
  ['lsingularityfunction_39',['LSingularityFunction',['http://www.dealii.org/developer/doxygen/deal.II/classFunctions_1_1LSingularityFunction.html',1,'Functions']]],
  ['lsingularitygradfunction_40',['LSingularityGradFunction',['http://www.dealii.org/developer/doxygen/deal.II/classFunctions_1_1LSingularityGradFunction.html',1,'Functions']]],
  ['lsrkstepperssp_41',['LSRKStepperSSP',['http://www.dealii.org/developer/doxygen/deal.II/classSUNDIALS_1_1LSRKStepperSSP.html',1,'SUNDIALS']]],
  ['lsrksteppersts_42',['LSRKStepperSTS',['http://www.dealii.org/developer/doxygen/deal.II/classSUNDIALS_1_1LSRKStepperSTS.html',1,'SUNDIALS']]]
];
